version: '2'
services:
  database:
    extends:
      file: ../common/docker-compose.yml
      service: database
    environment:
      POSTGRES_USER: "postgres_dev"
      POSTGRES_PASSWORD: "p0stgr@s_dev"
      POSTGRES_DB:       "eagle_eye_dev"

  config-service:
    extends:
      file: ../common/docker-compose.yml
      service: config-service

  licensing-service:
    image: smia/$SMIA_USER/tmx-licensing-service:chapter3
    ports:
      - "8080"
    environment:
      PROFILE: "dev"
      CONFIG_SERVICE_URI: "http://config-service:8888"
      CONFIG_SERVICE_PORT:   "8888"
      DATABASE_PORT: "5432"
      ENCRYPT_KEY: "IMSYMMETRIC"
