version: '2'
services:
  config-service:
    image: smia/$SMIA_USER/tmx-config-service:chapter3
    ports:
       - "8888"
    environment:
      ENCRYPT_KEY:       "IMSYMMETRIC"

  database:
    image: postgres:9.5
    ports:
      - "5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "p0stgr@s"
      POSTGRES_DB:       "eagle_eye_local"

  licensing-service:
    image: smia/$SMIA_USER/tmx-licensing-service:chapter3
    ports:
      - "8080"
    environment:
      PROFILE: "default"
      CONFIG_SERVICE_URI: "http://config-service:8888"
      CONFIG_SERVICE_PORT:   "8888"
      DATABASE_PORT: "5432"
      ENCRYPT_KEY:       "IMSYMMETRIC"
